name       : gimagereader
version    : 3.3.1
release    : 19
source     :
    - https://github.com/manisandro/gImageReader/releases/download/v3.3.1/gimagereader-3.3.1.tar.xz : 7688c9c20cbf2fa4f5b6ba0a8d77bd8d2e5929882ed965c7c07ccc529673f0dd
license    : GPL-3.0-or-later
component  : office
summary    : gImageReader is a simple Gtk/Qt front-end to tesseract
description: |
    gImageReader is a simple Gtk/Qt front-end to tesseract
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(gtksourceviewmm-3.0)
    - pkgconfig(gtkspellmm-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libxml++-2.6)
    - pkgconfig(libzip)
    - pkgconfig(poppler)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(sane-backends)
    - pkgconfig(tesseract)
    - podofo-devel
setup      : |
    %cmake -DINTERFACE_TYPE=gtk -DENABLE_VERSIONCHECK=OFF .
build      : |
    %make
install    : |
    %make_install
