name       : gimagereader
version    : 3.1.99
release    : 3
source     :
    - https://github.com/manisandro/gImageReader/releases/download/v3.1.99/gimagereader-3.1.99.tar.xz : ffc267c3703a0d9d93455d4e838282b1a7f7debce101a6ec5a01d3c7c9abe50c
license    : GPL-3.0
component  : office
summary    : gImageReader is a simple Gtk/Qt front-end to tesseract
description: |
    gImageReader is a simple Gtk/Qt front-end to tesseract
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(gtksourceviewmm-3.0)
    - pkgconfig(gtkspellmm-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libxml++-2.6)
    - pkgconfig(poppler)
    - pkgconfig(sane-backends)
    - pkgconfig(tesseract)
    - libjpeg-turbo-devel
    - podofo-devel
setup      : |
    %cmake -DINTERFACE_TYPE=gtk .
build      : |
    %make
install    : |
    %make_install
