name       : gimagereader
version    : 3.2.1
release    : 5
source     :
    - https://github.com/manisandro/gImageReader/releases/download/v3.2.1/gimagereader-3.2.1.tar.xz : 8dc08ca6f36f4c226203fa7fdb2709953d69309dcc78263621231d89d1c1c26e
license    : GPL-3.0
component  : office
summary    : gImageReader is a simple Gtk/Qt front-end to tesseract
description: |
    gImageReader is a simple Gtk/Qt front-end to tesseract
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(gtksourceviewmm-3.0)
    - pkgconfig(gtkspellmm-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libxml++-2.6)
    - pkgconfig(poppler)
    - pkgconfig(sane-backends)
    - pkgconfig(tesseract)
    - libjpeg-turbo-devel
    - podofo-devel
setup      : |
    %cmake -DINTERFACE_TYPE=gtk .
build      : |
    %make
install    : |
    %make_install
